apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b7okjmjvh-nodejs
  janus-idp.io/tekton: b7okjmjvh-nodejs
  backstage.io/kubernetes-id: b7okjmjvh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b7okjmjvh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
